name: PR Checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Kotlin compiler
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin

      - name: Compile and run TransactionDataSourceTest.kt
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          kotlinc test/data/TransactionDataSourceTest.kt src/finance/dataSource/*.kt src/finance/model/*.kt src/finance/logic/*.kt -include-runtime -d transaction-tests.jar
          java -jar transaction-tests.jar

      - name: Compile and run TransactionManagerTest.kt
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          kotlinc test/logic/TransactionManagerTest.kt src/finance/dataSource/*.kt src/finance/model/*.kt src/finance/logic/*.kt -include-runtime -d transaction-manager-tests.jar
          java -jar transaction-manager-tests.jar
