name: PR Checks

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Kotlin compiler
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin

      - name: Compile and run FinanceTrackerTests
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          kotlinc \
          test/data/TransactionDataSourceTest.kt \
          test/logic/TransactionManagerTest.kt \
          src/finance/dataSource/*.kt \
          src/finance/model/*.kt \
          src/finance/logic/*.kt \
          src/finance/*.kt \
          -include-runtime -d tests.jar \
          -Xinclude-runtime \
          -Xmain-class=test.data.TransactionDataSourceTestKt
          
          java -jar tests.jar
